

# --------------------------------
# BASE

server:
  port: 10081
  servlet.context-path: /v0.2

# NONE -응용 프로그램은 웹 응용 프로그램으로 실행되지 않아야하며 내장 웹 서버를 시작해서는 안됩니다.
# REACTIVE -애플리케이션은 반응 형 웹 애플리케이션으로 실행되어야하며 내장 된 반응 형 웹 서버를 시작해야합니다.
# SERVLET -애플리케이션은 서블릿 기반 웹 애플리케이션으로 실행되어야하며 임베디드 서블릿 웹 서버를 시작해야합니다.
spring.main.web-application-type: NONE


spring:
  profiles.active:
  - proj-default
  - proj-air
  - proj-pro
  #- proj-aws
  #- proj-dfep
  #- proj-real
#  h2.console:
#    enabled: true
#    path: /h2
#    settings:
#      trace: false
#      web-allow-others: true
#  datasource:
#    url: jdbc:h2:tcp://localhost:9092/fiudb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
#  jpa:
#    show-sql: true
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: update
#    properties:
#      hibernate.jdbc.time-zone: UTC+9
#  data.rest:
#    base-path: /api
#    default-page-size: 5
#    max-page-size: 50
#  thymeleaf:
#    enabled: true
#    encoding: utf-8
#    cache: false
#    prefix: classpath:templates/
#    suffix: .html
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  devtools:
    livereload.enabled: false


logging:
  file:
    path: logs/fiuclient/
    max-size: 10MB
    max-history: 30         # delete after a month
  pattern:
    console: "%clr(%d{HH:mm:ss} %p){magenta} - %m%n"
    file: "%d %-5level [%-10thread] [%-30logger{30}] - %m%n"
  level:
    root: info
    org.tain.*: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.thymeleaf: info
    org.h2.server.web: info
    
    #org.tain.utils.TransferStrAndJson: trace


---
# --------------------------------------------------------
spring.profiles: proj-default

proj-env:
  base:
    name: FIU CTR API project
    program: KieaFiu CTR API program
    version: ver 0.2_2020.11.11
    comment: This is FIU CTR API project.
  param:
    name: PARAM (default)
  job:
    name: JOB (default)
  json:
    name: JSON (default)
  url:
    name: URL (default)

---
# --------------------------------------------------------
# proj-local kang-air
spring.profiles: proj-air

proj-env:

  param:
    name: PARAM (air)
    home: /Users/kang-air
    base: /KANG/fiu/20201111
    info-path: /jsonInfo
    data-path: /jsonData
    send-path: /SEND
    sent-path: /SENT
    recv-path: /RECV
    file-ext: env

  job:
    name: JOB (air)

  json:
    name: JSON (air)
    apis-info-file: apis.json

  url:
    name: URL (air)
    connect-host: 127.0.0.1
    connect-port: 22010

---
# --------------------------------------------------------
# proj-test kang-mac
spring.profiles: proj-pro

proj-env:

  param:
    name: PARAM (pro)
    home: /Users/kangmac
    base: /KANG/fiu/20201111
    info-path: /jsonInfo
    data-path: /jsonData
    send-path: /SEND
    sent-path: /SENT
    recv-path: /RECV
    file-ext: env

  job:
    name: JOB (pro)

  json:
    name: JSON (pro)
    apis-info-file: apis.json

  url:
    name: URL (pro)
    connect-host: 127.0.0.1
    connect-port: 22010

---
# --------------------------------------------------------
# proj-aws
spring.profiles: proj-aws

proj-env:
  param:
    name: PARAM (aws)
  job:
    name: JOB (aws)
  json:
    name: JSON (aws)
  url:
    name: URL (aws)

---
# --------------------------------------------------------
# proj-dfep
spring.profiles: proj-dfep

proj-env:

  param:
    name: PARAM (dfep)
    home: /hw01/ibridge
    base: /KANG/fiu/20201111
    info-path: /jsonInfo
    data-path: /jsonData
    send-path: /SEND
    sent-path: /SENT
    recv-path: /RECV
    file-ext: env

  job:
    name: JOB (dfep)

  json:
    name: JSON (dfep)
    apis-info-file: apis.json

  url:
    name: URL (dfep)
    connect-host: 125.60.18.30
    connect-port: 22010

---
# --------------------------------------------------------
# proj-real
spring.profiles: proj-real

proj-env:
  param:
    name: PARAM (real)
    home: /hw01/ibridge
    base: /KANG/fiu/20201111
    info-path: /jsonInfo
    data-path: /jsonData
    send-path: /SEND
    sent-path: /SENT
    recv-path: /RECV
    file-ext: env

  job:
    name: JOB (real)

  json:
    name: JSON (real)

  url:
    name: URL (real)
    connect-host: 125.60.18.30
    connect-port: 22010


